CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	lastname VARCHAR (50) NOT NULL,
	email VARCHAR(50) UNIQUE NOT NULL,
	password VARCHAR(50) NOT NULL
);

CREATE TABLE tracks (
	id BIGSERIAL PRIMARY KEY,
	time DECIMAL NOT NULL,
	note VARCHAR (200) NOT NULL,
	date DATE NOT NULL,
	user_id BIGINT REFERENCES users NOT NULL
);